site_name: YHProduction Wiki
repo_url: https://github.com/yzip/YHProduction.Wiki
pages:
- 主页: index.md
- 规则须知:
    - 论坛规则: CommunityPrinciples/CommunityGuidelines.md
    - 管理规则: CommunityPrinciples/SupportGuidelines.md
- 入门:
    - 安装 GE: GettingStarted/Installation.md
    - 功能详解: GettingStarted/Features.md
    - 支持的英雄: GettingStarted/SupportedChampions.md
    - 常见问题: GettingStarted/FrequentlyAskedQuestions.md
- 故障解决:
    - 如何汇报问题: Troubleshooting/TroubleshootingReportGuide.md
    - 论坛使用帮助: Troubleshooting/WebsiteTroubleshooting.md
    - 软件使用帮助: Troubleshooting/ApplicationTroubleshooting.md
    
theme: readthedocs
